% The ATD code is created by Shancong Mou
clc;clear
% generate data
d1=30;d2=40;d3=40;
Sm1 = genCircleSm(d2,d3);% heating effect
Sm2 = genLinearSm(d2,d3);% cooling effect
Sm = zeros(d3,d2,d1);
for i =1 : d1
    rnd = rand
    Sm(:,:,i) = rnd*Sm1+(1-rnd)*Sm2;
end
Sp_m = genSpError3( d1, d2, d3, [1:d1]);% moving hot spot
Sp_s = genSpError1( d1, d2, d3, [1:d1]);% static hot spot
M = Sm+Sp_s+Sp_m;
%% ATD
lam = 1;
lam1 = 30;
lam2 = 1.9;
lam3 = 2.0;
errtol = 1e-6;
tic
[L,S_s,S_m] = ATDExp2(M,lam,lam1,lam2,lam3,errtol);
toc
%% RPCA code is generated by Dmitry Laptev, https://github.com/dlaptev/RobustPCA
%%% For more information on Robust PCA please refer to the original paper 
%%% "Robust principal component analysis?" Emmanuel J. Candès, Xiaodong Li, Yi Ma and John Wright, 2009.
M_ = reshape(M,[],d1)
[L_, S_] = RobustPCA(M_)
L_RPCA =  reshape(L_,d2,d3,d1);
S_RPCA =  reshape(S_,d2,d3,d1);

%% plot
% 20th
for i =20:20
    figure('Renderer', 'painters', 'Position', [10 10 150 150])
    imagesc(M(:,:,i),[0,0.7])
    %colorbar
    set(gca,'XTick',[], 'YTick', [])
    title('Orignial image')

    figure('Renderer', 'painters', 'Position', [10 10 150 150])
    imagesc(L(:,:,i),[0,0.7])
    %colorbar
    set(gca,'XTick',[], 'YTick', [])
    title('ATD static backgorund')
    
    figure('Renderer', 'painters', 'Position', [10 10 150 150])
    imagesc(S_s(:,:,i),[0,0.1])
    %colorbar
    set(gca,'XTick',[], 'YTick', [])
    title('ATD static hotspot ') 

    figure('Renderer', 'painters', 'Position', [10 10 150 150])
    imagesc(S_m(:,:,i),[0,0.1])
    %colorbar
    set(gca,'XTick',[], 'YTick', [])
    title('ATD moving hotspot')
    
    figure('Renderer', 'painters', 'Position', [10 10 150 150])
    imagesc(L_RPCA(:,:,i),[0,0.7])
%     colorbar
    set(gca,'XTick',[], 'YTick', [])
    title('RPCA backgound')  
    figure('Renderer', 'painters', 'Position', [10 10 150 150])
    imagesc(S_RPCA(:,:,i),[0,0.1])
%     colorbar
    set(gca,'XTick',[], 'YTick', [])
    title('RPCA moving object') 

end 